#config_version=6
##! mode: attract
mode:
  priority: 50

show_player:
  mode_attract_started: 
    fadeshow:
      speed: 8
      loops: 3
      events_when_completed: start_attract_2
  start_attract_2:
    attract_light_show:
      speed: 4
      loops: 3
      events_when_completed: start_attract_3
  start_attract_3:
    fadeshow:
      speed: 8
      loops: 3
      events_when_completed: start_attract_2

slide_player:
# mode_attract_started: attract
  mode_attract_started: attract_scroll
  s_right_flipper1_active: 
    last_score:
      expire: '5s'
      priority: 100
  