#config_version=6
##! mode: attract
mode:
  priority: 50

show_player:
  #mode_attract_started: 
  #  fade_sweep:
  #    speed: 4
  mode_attract_started:
    attract_light_show:
      speed: 4

slide_player:
# mode_attract_started: attract
  mode_attract_started: attract_scroll
  s_right_flipper1_active: 
    last_score:
      expire: '5s'
      priority: 100
  