#config_version=6
##! mode: attic_double_score

mode:
  start_events: logicblock_cellar_hits_complete
  #restart_on_next_ball: true
  priority: 200
  stop_events:  main_pf_shots_ds_hit
  
shots:
  upper_pop_ds:
   switch: s_upper_pop
  upper_1_ds:
    switch: s_upper_1_target 
  upper_2_ds:
    switch: s_upper_2_target
  upper_3_ds:
    switch: s_upper_3_target
  upper_4_ds:
    switch: s_upper_4_target
  upper_1_drop_ds:
    switch: s_upper_1_drop
  upper_2_drop_ds:
    switch: s_upper_2_drop
  upper_3_drop_ds:
    switch: s_upper_3_drop
  upper_4_drop_ds:
    switch: s_upper_4_drop
    
  main_pf_shots_ds:
    switch:
      - s_main_2_trough

variable_player:

  upper_pop_ds_hit:
    score: 1000
  upper_1_ds_hit{device.counters.attic_drop_counter.value >= 0}:
    score: 3000
  upper_2_ds_hit{device.counters.attic_drop_counter.value < 1}:
    score: 500
  upper_2_ds_hit{device.counters.attic_drop_counter.value >= 1}:
    score: 3000
  upper_3_ds_hit{device.counters.attic_drop_counter.value < 2}:
    score: 500
  upper_3_ds_hit{device.counters.attic_drop_counter.value >= 2}:
    score: 3000
  upper_4_ds_hit{device.counters.attic_drop_counter.value < 3}:
    score: 500
  upper_4_ds_hit{device.counters.attic_drop_counter.value >= 3}:
    score: 3000
  upper_1_ds_drop_hit:
    score: 3000
  upper_2_ds_drop_hit:
    score: 3000
  upper_3_ds_drop_hit:
    score: 3000
  upper_4_ds_drop_hit:
    score: 3000

show_player:
  mode_attic_double_score_started: 
    flash_attic_db_score:
      speed: 3
  
shows:
  flash_attic_db_score:
    - time: 0
      lights: 
        l_attic_double_score: white
    - time: 1
      lights:
        l_attic_double_score: off
  